name: CI

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Ruff over code
        uses: chartboost/ruff-action@v1
