name: lint

on: push

jobs:
  lint:
    name: ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run Ruff over code
        uses: astral-sh/ruff-action@v4.1.0
